services:
  api:
    image: api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "5087:8080"
    networks:
      - PetShop_network

networks:
  PetShop_network:
    driver: bridge