services:
  petshop.api:
    image: petshop.api
    build:
      context: .
      dockerfile: PetShop.API/Dockerfile
      args:
        BUILD_CERT_PASSWORD: "3702959"
    environment:
      - ASPNETCORE_URLS="http://+:8080;https://+:443"
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certs/certificate.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=3702959

      # 🔥 Variáveis para conectar ao MongoDB
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=PetShopDB
      - MONGO_USER=admin
      - MONGO_PASS=admin123

    ports:
      - "5087:8080"
      - "7151:443"
    volumes:
      - ./Cambui.Account/temp/certificate.pfx:/app/certs/certificate.pfx:ro
    depends_on:
      - mongo
    networks:
      - PetShop_network

  mongo:
    image: mongo:6
    container_name: petshop_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: PetShopDB
    ports:
      - "27018:27017"   # Porta externa 27018 → interna 27017
    volumes:
      - mongo_data:/data/db  # Persistência
    networks:
      - PetShop_network

networks:
  PetShop_network:
    driver: bridge

volumes:
  mongo_data:
